baseURL = "https://jerrypan617.github.io/"
languageCode = 'en-us'
title = 'JerryLogs'
theme = "ananke"
publishDir = "docs"
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2